tardis_config_version: v1.0
supernova:
  luminosity_requested: 9.00 log_lsun
  time_explosion: 31.3 day
atom_data: /home/zzzaurak/THU/astro/obsastro-sn-pipeline/data/kurucz_cd23_chianti_H_He_latest.h5
model:
  structure:
    type: specific
    velocity:
      start: 7671.4 km/s
      stop: 16621.3 km/s
      num: 20
    density:
      type: power_law
      time_0: 1 day
      rho_0: 5e-10 g/cm^3
      v_0: 10000 km/s
      exponent: -7
  abundances:
    type: uniform
    He: 0.62
    O: 0.22
    C: 0.1
    Si: 0.035
    S: 0.015
    Ca: 0.01
plasma:
  ionization: lte
  excitation: lte
  radiative_rates_type: dilute-blackbody
  line_interaction_type: macroatom
montecarlo:
  seed: 23111963
  no_of_packets: 50000
  iterations: 10
  last_no_of_packets: 100000
  no_of_virtual_packets: 3
  nthreads: 8
  convergence_strategy:
    type: damped
    damping_constant: 0.5
    threshold: 0.05
    lock_t_inner_cycles: 1
    t_inner_update_exponent: -0.5
spectrum:
  start: 500 angstrom
  stop: 20000 angstrom
  num: 10000
  method: integrated
  integrated:
    compute: Automatic
    points: 1000
